### ISSUE TITLE
Lack of PREF cookie results in "quota exceeded" error

### ISSUE THREAD

**Issue by hyperair** [pedrofaustino/google-trends-csv-downloader#2]
When attempting to download Google Trends data, the authentication portion gets through fine (after https://github.com/pedrofaustino/google-trends-csv-downloader/pull/1), but get_csv() terminates, complaining that the quota has been exceeded.

However, manually logging in with a browser and clicking on the download CSV link appears to work. It looks like we aren't sending enough cookies back for some reason. Using Curl, I managed to narrow down the necessary cookies to:
- PREF
- HSID
- SID

However, it looks like we're not getting the PREF cookie at all during the login process. Very weird..

**Comment by pedrofaustino** [comment]
I suppose you're getting the 'Content-Disposition' header on the browser right? That's the one I'm checking against to see if the quota has been exceeded.

So you're saying you've inspected the cookies after the call
`resp = self.opener.open(self.url_login)`
and the lack of the PREF cookie is what breaks the code?

**Comment by hyperair** [comment]
On 10/12/2012 21:52, pedrofaustino wrote:

> I suppose you're getting the 'Content-Disposition' header on the browser right?
> That's the one I'm checking against to see if the quota has been exceeded.
> 
> So you're saying you've inspected the cookies after the call
> |resp = self.opener.open(self.url_login)|
> and the lack of the PREF cookie is what breaks the code?

Yeah, I think so. I actually modified the urllib2.build_opener call to add
HTTPHandler and HTTPSHandler with debuglevel=2 to spit out the headers, and
didn't see the PREF cookie getting exchanged at all.

Additionally, I inspected the contents of the response, and it's a HTML page
saying that an error has happened, but with no details whatsoever. It's the same
page that gets served if I use curl with the PREF cookie removed.

## 

Kind regards,
Loong Jin

**Comment by pedrofaustino** [comment]
Executing the python script doesn't throw that error. But going to the
browser and specifically deleting the PREF cookie is enough to get the
"reached quota" limit.

There's some URL that we need to ping to get that cookie which we are
missing. Reading
http://blogs.wsj.com/digits/2012/02/28/the-google-cookie-that-seems-to-come-out-of-nowhere/and
http://stackoverflow.com/questions/6301114/how-pref-cookie-google-com-appears-in-firefoxit
seems this cookie is also set with Safe Browsing requests?

Pedro

**Comment by hyperair** [comment]
On 11/12/2012 03:25, pedrofaustino wrote:

> Executing the python script doesn't throw that error. But going to the
> browser and specifically deleting the PREF cookie is enough to get the
> "reached quota" limit.

It doesn't? How are you executing it? I used a test script which looks like:

------------8<--------------
from pyGoogleTrendsCsvDownloader import pyGoogleTrendsCsvDownloader

downloader = pyGoogleTrendsCsvDownloader('username', 'password')
downloader.get_csv(q='test')
------------>8--------------

## 

Kind regards,
Loong Jin

**Comment by pedrofaustino** [comment]
The query I'm doing is the one given in the comments
get_csv(cat='0-958', geo='US-ME-500')

Pedro

**Comment by hyperair** [comment]
On 11/12/2012 17:32, pedrofaustino wrote:

> The query I'm doing is the one given in the comments
> get_csv(cat='0-958', geo='US-ME-500')

Hmm, strangely enough I got it to work thrice, and then it stopped working again.

## 

Kind regards,
Loong Jin

**Comment by ucb** [comment]
Guys! Do you have any new on the issue? Manual downloads are killing me ;(

And I get the same symptoms: downloading works through a browser, but not using Python...

I am sure you have fixed it by now: do not make it a secret...

**Comment by pedrofaustino** [comment]
I'm not able to replicate the issue in Python.
I'd advise you to either try to find a way of getting the PREF cookie through Python, or just dump your google cookie from the browser to a Python cookiejar and use it.

**Comment by ucb** [comment]
To be honest, I have not used Python before. Hence, I do not know whether and/or which cookies are causing it (I only downloaded simple http and ftp addresses in perl).

What I know is that I am getting this message "You've exceeded your quota. Continue tomorrow..." when I run get_csv(cat='0-958', geo='US-ME-500') from the comments.

What should be changed in pyGoogleTrendsCsvDownloader?

**Comment by hyperair** [comment]
I haven't been able to get it to work more than 3 times per day. After that it just gives me the quota exceeded message. I'm not even sure if the PREF cookie is the source of the issue now, because I can't download CSVs manually either until the quota is reset the next day.

**Comment by ucb** [comment]
Interesting as I can download manually: no problem (except for the problem of time costs). I get an error only doing when running python.

**Comment by pedrofaustino** [comment]
I'm afraid I can't help much since I'm not able to replicate this issue at
my end.

Pedro

**Comment by ucb** [comment]
Now it is that proverbial "tomorrow" I get the same problem as  Hyperair. get_csv comes through ca. three times and dies with the quota error.

Manual download still works for me though...

Pedro, do you use pyGoogleTrendsCsvDownloader directly or have you made any changes?

Cheers

**Comment by pedrofaustino** [comment]
I don't use it anymore and I haven't made any changes. If I had, I would
have committed them...after all that was the whole point of sharing the
code (existing scripts were not working for me).

Pedro

**Comment by ucb** [comment]
what do you use instead? I will use anything that will save me from doing it manually...

**Comment by pedrofaustino** [comment]
I don't use it anymore because atm I don't need Google Trends data (project
has finished).

Pedro

**Comment by ucb** [comment]
It is a pity.

The only thing I thought of is increasing the delay constant: setting it to 2.25 did not have any desired result.

What would you recommend?

**Comment by hyperair** [comment]
On 10 Feb, 2013 5:17 AM, "ucb" notifications@github.com wrote:

> It is a pity.
> 
> The only thing I thought of is increasing the delay constant: setting it
> to 2.25 did not have any desired result.
> 
> What would you recommend?

Haha I don't know either.  I haven't  managed to get it to work past three
tries per day either.

What I have been doing is running three transfers a day.

**Comment by ucb** [comment]
Hmmm... at three per day I will be done in several years...

**Comment by jhezghia** [comment]
Nice code.  I'm having trouble though with trying to download specific dates.  Is this code able to handle specific dates from Google trends?

Thanks

**Comment by hyperair** [comment]
No, I don't believe Google's interface allows for that.

**Comment by pedrofaustino** [comment]
Closing issue. Please open a new ticket for other issues
