### ISSUE TITLE
Extracting Data Within Certain Date Ranges

### ISSUE THREAD

**Issue by jhezghia** [pedrofaustino/google-trends-csv-downloader#3]
I'm having trouble though with trying to download specific dates. Google Trends itself allows for this (for example: http://www.google.com/trends/explore#q=hi&date=1%2F2007%203m&cmpt=q).  I'm having trouble passing this into get_csv however.  Does anyone know how to handle this?  

I made some changes to the code to try to hack this out.  

```
    params.update(kwargs)
    params = urllib.urlencode(params)
    params = params.replace('+', '%20')

    #So what's going on is that urlencode wants to encode the space in the
    #trendsReport date variable as a +, when we want it encoded as a space,
    #which in HTMl encoding is %20.

    complete_url = self.url_download + params
    print complete_url

    r = urllib2.urlopen(complete_url)
```

My usage is:

```
    r.get_csv(q='job', geo='US-'+state, date='1/2012 7m')
```

When I put the url generated into the browser, it works.  But I get the quota error when I try running it on python.

Thanks

**Comment by pedrofaustino** [comment]
I'm not able to help you with the "quota exceeded error".

Regarding the enconding, Google Trends seems to accept both %20 or + (when using the browser), so I don't think we need to change the code. Your usage seems correct.

**Comment by 321k** [comment]
You need to authenticate with Google before you can access the data. I've been trying to get it to work myself, but something seems to have changed with authentication. My workaround is to use getURL to download the files to my harddrive, and then read them into R. It's not ideal, but if you ask firefox not to prompt you when downloading, it's at least automatic.

**Comment by simonavril** [comment]
I also have experienced that:
`params = params.replace('+', '%20')`
is needed to get the date query working through urlopen. It might be worth updating the code since the error message 'quota exceeded error' that is returned is confusing.
