### ISSUE TITLE
not working as of 30th may 2013

### ISSUE THREAD

**Issue by anonsub26** [pedrofaustino/google-trends-csv-downloader#4]
Hello the code is not working for me as of today. :(

i always get "You've exceeded your quota. Continue tomorrow..." although i can still download csv via the browser and the same account.

Maybe you could try to make it working again.

THX

yours John

**Comment by anonsub26** [comment]
On this page there is a solution in C# which works since 30.04.2013 ("As of 4/30/2013 this works..."). Can you anyhow make use of the idea for python?

**Comment by pedrofaustino** [comment]
Which page?

**Comment by anonsub26** [comment]
Sorry pedro, i forgot to post the page.

http://stackoverflow.com/questions/4986758/oauth-google-trends-download-csv-file

After "As of 4/30/2013 this works..." there is c# code which is claimed to be able to automatically download Google Trends data. Maybe you can adapt it to your python code. this would be great. :)

**Comment by adamchapman** [comment]
I still hit a quota limit when using the method ggjj11 linked. Is anybody else experiencing similar problems?

**Comment by anonsub26** [comment]
Have you implemented the method in python? If so, could you please release it so i can also try it?

**Comment by adamchapman** [comment]
I only tried that method in Matlab, and have started using this: https://gist.github.com/tlmaloney/5650699 instead, as the author mentioned in a forum (https://www.quantopian.com/posts/google-search-terms-predict-market-movements) that he wasn't hitting any limits with that. 

I'm running that python code from matlab now, but it falls over when requesting multiple search terms

**Comment by anonsub26** [comment]
Great. Thank you for pointing out this tool :+1:

**Comment by adamchapman** [comment]
Unfortunately I hit the quota limit using this method yesterday. I haven't heard back from the author.

Could you please try it and tell me if you hit a quota limit too?

**Comment by eawtrey** [comment]
A little playing around reveals that Google is blocking this by IP address (no real surprise).  Therefore, a workaround that I just successfully used was getting a fresh IP address from the local DHCP server.  This buys me a new round of searches (3 or 4), and then I need to refresh the IP again.  

Refreshing the IP address isn't straightforward, but not too bad (and better than running manual searches!).  You can use a locally assigned MAC address as described in the comment by Keltari here: http://superuser.com/a/600299

Until we get to the bottom of the quota issue, this makes a nice partial solution.

**Comment by adamchapman** [comment]
I've been using a VPN to change IP, which give me another 4 searches on average. changing the IP again will give me another 4 searches and so on. 

I would have thought that using a VPN would completely release the quota- Google must be able to see some other information to identify that this machine can not have another 1000 searches. 

If anybody has some ideas to what the extra info is, I'd be very interested to hear it.

**Comment by simonavril** [comment]
I did notice that this code now limits the queries to about 4/day. I investigated further and it seems that  now a cookie call PREF is needed. 

Adding:

`ck2 = Cookie(version=0, name='PREF', value='', port=None, port_specified=False, domain='.google.com', domain_specified=False,domain_initial_dot=False, path='', path_specified=False, secure=False, expires=None, discard=False, comment=None, comment_url=None, rest=None)`

and  
`self.cj.set_cookie(ck2)`

fixes it for me

**Comment by pedrofaustino** [comment]
Closing this ticket after merging @simonavril PR (commit 93e629ab7f68ab9ede4bf1ed3ddab09b42413d7f).
